name = "legends-of-spire"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "legends-db"
database_id = "b2f45e9b-7bc1-417b-ab9a-7a2ad9b503eb"

